remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

title: What to Ask Your Website Company
description: Getting a website that actually works for your business

minimal_mistakes_skin: "default"
