remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache

title: What to Ask Your Website Company
description: Getting a website that actually works for your business

minimal_mistakes_skin: "default"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-6EEHKP4YCH"
    anonymize_ip: false

author:
  name: "Dave Cross"
  email: "dave@davecross.co.uk"
  social:
    - "https://github.com/davorg"
    - "https://www.linkedin.com/in/davorg/"

social:
  name: "What to Ask Your Website Company"
  links:
    - "https://github.com/davorg"
    - "https://www.linkedin.com/in/davorg/"
  image: "/assets/images/image-og.png"

twitter:
  username: "@davorg"
  card: "summary"

json_ld:
  enabled: true
  type: "Person"  # "Person" if personal blog, "Organization" for business
  name: "Dave Cross"
  description: "A guide for small businesses looking to build or improve their website."
  url: "https://websiteguide.davecross.co.uk/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_title: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_title: false
