remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap

title: What to Ask Your Website Company
description: "Getting a website that actually works for your business - A guide for small businesses looking to build or improve their website."

minimal_mistakes_skin: "default"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-6EEHKP4YCH"
    anonymize_ip: false

author:
  name: "Dave Cross"
  email: "dave@davecross.co.uk"
  social:
    - "https://github.com/davorg"
    - "https://www.linkedin.com/in/davorg/"

og_image: "/assets/images/website-build.png"

social:
  name: "What to Ask Your Website Company"
  links:
    - "https://github.com/davorg"
    - "https://www.linkedin.com/in/davorg/"
  image: "/assets/images/image-og.png"

twitter:
  username: "@davorg"
  card: "summary"

json_ld:
  enabled: true
  type: "Person"  # "Person" if personal blog, "Organization" for business
  name: "Dave Cross"
  description: "A guide for small businesses looking to build or improve their website."
  url: "https://websiteguide.davecross.co.uk/"

header:
  nav: false

atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_title: false
      sidebar:
        nav: "side"
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_title: false
      sidebar:
        nav: "side"
  -   aside:
        - type: custom
          content: |
            <p><a class="btn btn--primary" href="/assets/pdf/websiteguide2025.pdf" target="_blank">📄 Download as PDF</a></p>
